
site_name: Python Fundamentals


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    


theme:
  name: 'material'
  highlightjs: true
  hljs_languages: [python]
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 

  
  
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni
      


nav:
- Home: index.md
- Guide to Installing Python: GettingStarted/anaconda.md
- Guide to Python Libraries: GettingStarted/lib.md
- Setting up Python Environment: GettingStarted/env.md
- Installing Jupyter Notebook : GettingStarted/jupyter.md
- How to Git: GettingStarted/git.md
- DataStructure: DataStructure/ds.md
- Loops and Conditions: LoopsConditions/lnc.md
- Functions and Class : FunctionClass/fnc.md
- Handeling Errors: Errors/lfr.md
- Input Output: IO/io.md
- Python Standard Library: StandardLibrary/psl.md
- Project Fern: Projects/Fern/fern.md
- Project Random Walk: Projects/Rwalk/Rwalk.md
- Project N-charges: Projects/Ncharges/Ncharges.md
- Project Diffusion: Projects/Diffusion/Diffusion.md
- Reference: References/ref.md
 
 
 
 
 
