
site_name: Python


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    


theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni


nav:
- Home: index.md
- Why Codes?: WhyCodes.md

- Getting started:
  - Guide to starting Python: GettingStarted/anaconda.md
  - Guide to Python Libraries: GettingStarted/lib.md
  - Setting up Python Environment: GettingStarted/env.md
  - Installing Jupyter Notebook : GettingStarted/jupyter.md
  - How to Git: GettingStarted/git.md
  
- Python Programming:
  - Introduction: prog.md
  - DataStructure: DataStructure/ds.md
  - Loops and Conditions: LoopsConditions/lnc.md
  - Project Fern: Projects/Fern/fern.md
  - Project Diffusion: Projects/Diffusion/Diffusion.md
  - Functions and Class : FunctionClass/fnc.md
  - Project N-charges: Projects/Ncharges/Ncharges.md
  - Project Random Walk: Projects/Rwalk/Rwalk.md
         
  
- Numpy:
  - Introduction: Numpy/numpy.md
  - Array: Numpy/array/array.md
  - MeshGrid: Numpy/grid/meshgrid.md
  - Algebra: Numpy/algebra/algebra.md
  - Statistics: Numpy/stat/stat.md
  

- Pandas:
  - Introduction: Pandas/pandas.md
  - Dataframe: Pandas/DataFrame/dataframe.md
  - Indexing: Pandas/Indexing/Indexing.md
  - Data Exploration: Pandas/Explor/explor.md
  - GroupBy: Pandas/GroupBy/groupby.md
  - Lambda Transform : Pandas/Lambda/lambda.md

  
- Linear Models:
  - Regression: LinearModels/Linear-models.md
  
- Classification:
  - Logistic: Classifiers/Logistic/Logistic.md
  - Decision Tree: Classifiers/Tree/Tree.md
  - Ensamble: Classifiers/Ensamble/ensamble.md
  - SVM: Classifiers/SVM/svm.md
  
- References:
  - Reference: References/ref.md
 
 
 
 
 
